#' @export
data.input.help<-function(){
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus dictum lectus ut eros pharetra luctus. Pellentesque dictum nisi et iaculis elementum. Integer neque ligula, euismod ut diam in, sollicitudin suscipit libero. Maecenas ultrices, odio a aliquet tempor, dolor sem fermentum urna, ut ullamcorper purus metus at mi. Aenean maximus purus non neque tempor vestibulum sed eu felis. Aenean molestie consequat purus, eget fermentum orci tristique a. Aenean porttitor fringilla urna, non mattis ligula cursus a. Nulla placerat mattis elit blandit suscipit. Ut eu aliquam lectus, nec congue urna.
  
  Donec varius leo non eros accumsan euismod. Proin eget ornare ante. Quisque sodales velit sit amet bibendum dictum. Nullam eget nunc ipsum. Donec elementum, lacus vitae pharetra lobortis, dui quam ornare metus, in sagittis mi nisi sit amet justo. Maecenas at varius mi. Integer vestibulum ornare cursus. Integer tristique imperdiet urna ac iaculis. Etiam sit amet tempor felis. Curabitur ut dui eu dolor consequat dictum id eget lacus. Nunc sed pulvinar turpis.
  
  Suspendisse venenatis rutrum mauris, quis sollicitudin dui efficitur vel. Aliquam nec odio rhoncus, gravida purus non, dapibus leo. Donec vehicula tellus volutpat purus vulputate rhoncus. Sed id rhoncus lectus. Aenean congue posuere erat, non scelerisque metus vehicula vel. Nunc venenatis, lorem ut vulputate semper, mi nisi porta quam, eget ultrices purus tellus eget sapien. Nulla placerat at arcu at condimentum. Nunc fringilla turpis at lorem facilisis commodo. In vel interdum risus. Vestibulum blandit sed sem sed pharetra. Praesent venenatis egestas tristique. Donec ut libero ac odio hendrerit aliquam eget id arcu.
  
  Mauris venenatis magna ut fermentum luctus. Praesent vehicula tincidunt dolor sit amet pellentesque. Integer eget libero auctor, molestie tellus in, ornare neque. Sed sollicitudin lacus ac nulla mattis laoreet. Curabitur sed porta ex. Curabitur vel consequat justo, sed gravida tellus. Pellentesque nisi orci, pretium at congue at, blandit sit amet risus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed velit orci, tristique at quam a, finibus bibendum justo. Nulla ut eros massa.
  
  Cras fringilla scelerisque ligula, nec pharetra elit tincidunt sed. Ut ipsum ipsum, facilisis vitae ex quis, suscipit blandit risus. Nunc consequat odio eget dui cursus, et fermentum tellus convallis. Donec id blandit mauris. Nunc suscipit lacus eu vestibulum lobortis. Suspendisse mauris felis, ultricies a metus eget, malesuada rhoncus libero. Donec sollicitudin metus neque, ac finibus augue pharetra ac. Morbi gravida ligula eget condimentum dictum."
}